const FETCH_TASKS = 'FETCH_TASKS';
const SET_TASKS = 'SET_TASKS';
const SET_ERROR = 'SET_ERROR';
const CREATE_TASK = 'CREATE_TASK';
const SET_CREATE_TASK_CONFIRMATION_STATUS = 'SET_CREATE_TASK_CONFIRMATION_STATUS';
const COMPLETE_TASK = 'COMPLETE_TASK';
const DELETE_TASK = 'DELETE_TASK';

export default {
  FETCH_TASKS,
  SET_TASKS,
  SET_ERROR,
  CREATE_TASK,
  SET_CREATE_TASK_CONFIRMATION_STATUS,
  COMPLETE_TASK,
  DELETE_TASK
};